[package]
name = "jgu-mpcs-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = [
	"Moelf <https://github.com/Moelf>",
	"inverted-tree <https://github.com/inverted-tree>",
	]
license = "MIT"
description = "Inofficial Math/Physics/Computer-Science Thesis Template for the Johannes-Gutenberg University based on the Harvard Dissertation Formatting Guidance and JGU Corporate Design Manual."
repository = "https://github.com/inverted-tree/jgu-typst-mpcs-thesis"
keywords = [
	"Harvard",
	"Harvard University",
	"JGU",
	"Johannes-Gutenberg University",
	"Thesis",
	"Mathmatics",
	"Physics",
	"Computer Science",
	]
categories = ["thesis"]

[template]
path = "templates"
entrypoint = "thesis.typ"
thumbnail = "img/thumbnail.png"
