[package]
name = "jgu-cs-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = [
	"Moelf <https://github.com/Moelf>",
	"inverted-tree <https://github.com/inverted-tree>",
	]
license = "MIT"
description = "Computer Science Thesis Template for the Johannes-Gutenberg University based on the Harvard Dissertation Formatting Guidance"
repository = "https://github.com/inverted-tree/jgu-typst-cs-thesis"
keywords = [
	"Harvard",
	"Harvard University",
	"JGU",
	"Johannes-Gutenberg University",
	"Thesis",
	"Computer Science",
	"CS"
	]
categories = ["thesis"]

[template]
path = "templates"
entrypoint = "main.typ"
thumbnail = "img/thumbnail.png"
